name = "optgra"
author = "Jacob Williams"
maintainer = "Jacob Williams"
description = "optgra"
homepage = "https://github.com/jacobwilliams/optgra"

[build]
auto-executables = false
auto-examples = false
auto-tests = true


[library]
source-dir = "src"

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "fixed"

