ogleft – optgra
ogleft Function
15 statements
Source File
private function ogleft(me, Actinp) result(Actout)
LEFT-MULTIPLIES VECTOR LOWER TRIANGULAR MATRIX OBTAINED BY REDUCTION AND SUBSEQUENT INVERSION OF DERIVATIVES OF ACTIVE CONSTRAINTS
2008/01/16 | J. SCHOENMAEKERS | NEW
Type Bound
optgra
Arguments
Type Intent Optional Attributes Name
class(optgra), intent(inout) :: me
real(kind=wp), intent(in) :: Actinp(me%Numcon)
VECTOR INITAL
Return Value real(kind=wp), (me%Numcon)
VECTOR FINAL
Called by
Source Code
   function ogleft(me,Actinp) result(Actout)
      !! LEFT-MULTIPLIES VECTOR LOWER TRIANGULAR MATRIX OBTAINED BY REDUCTION
      !! AND SUBSEQUENT INVERSION OF DERIVATIVES OF ACTIVE CONSTRAINTS
      !!
      !! 2008/01/16 | J. SCHOENMAEKERS | NEW
      class(optgra),intent(inout) :: me
      real(wp),intent(in) :: Actinp(me%Numcon) !! VECTOR INITAL
      real(wp) :: Actout(me%Numcon) !! VECTOR FINAL
      integer(ip) :: row , col , act
      real(wp) :: val
      do act = 1 , me%Numact
         row = me%Actcon(act)
         val = Actinp(act)
         do col = 1 , act - 1
            val = val - me%Conred(row,col)*Actout(col)
         end do
         Actout(act) = val/me%Conred(row,act)
      end do
   end function ogleft
Call graph
ogopti calls ogleft
ogsens calls ogleft
ogexec calls ogopti