ogpwri_start – optgra
ogpwri_start Subroutine
25 statements
Source File
private subroutine ogpwri_start(me)
WRITE OPTIMIZATION LOG IN PYGMO FORMAT
2023/01/25 | W. MARTENS | NEW
Type Bound
optgra
Arguments
Type Intent Optional Attributes Name
class(optgra), intent(inout) :: me
Called by
Source Code
   subroutine ogpwri_start(me)
      !! WRITE OPTIMIZATION LOG IN PYGMO FORMAT
      !!
      !! 2023/01/25 | W. MARTENS | NEW
      class(optgra),intent(inout) :: me
      write (me%Loglup,'("OPTGRA plugin for pagmo/pygmo:")')
      select case (me%Varder) ! DERIVATIVES COMPUTATION MODE
       case ( 0 );      write (me%Loglup,'("")') ! VALUES ONLY
       case ( 1, -1 );  write (me%Loglup,'("    User-defined gradients")')
       case ( 2 );      write (me%Loglup,'("    Numerical gradients by double differencing")')
       case ( 3 );      write (me%Loglup,'("    Numerical gradients by single differencing")')
      end select
      select case (me%Optmet)
       case ( 0 ); write (me%Loglup,'("    Steepest descent method")')
       case ( 1 ); write (me%Loglup,'("    Modified spectral conjugate gradient method")')
       case ( 2 ); write (me%Loglup,'("    Spectral conjugate gradient method")')
       case ( 3 ); write (me%Loglup,'("    Conjugate gradient method")')
      end select
      write (me%Loglup,'("")')
   end subroutine ogpwri_start
Call graph
ogpwri calls ogpwri_start
ogeval calls ogpwri
ogcorr calls ogeval
ogexec calls ogeval, ogcorr, ogopti
ogopti calls ogeval